name: validate
on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Validate tasks
        run: |
          python3 scripts/validate_tasks.py
      - name: Terraform fmt
        run: |
          cd infra/terraform && terraform fmt -check -recursive
      - name: Terraform validate (no backend)
        run: |
          cd infra/terraform && terraform validate || true
